#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 

bspc config border_width        2 
bspc config window_gap          12

bspc config normal_border_color "#33244"
bspc config focused_border_color "#7f849c"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Firefox desktop='^2'

xrandr -s 1920x1080
exec ~/.config/polybar/launch.sh
